template: true
valuesFilePath: ./values.yml

resources:
  - name: {{ .Values.primaryResource }}
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: {{ .Values.protocol }}
      buildOn:
        commit: {{ .Values.publishOnCommit }}

pipelines:
  - name: {{ .Values.pipelineName }}_publish
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          TASK_NAME: {{ .Values.taskName }}
          TASK_VERSION: 0.0.1
          TASK_REPOSITORY: pipelines-tasks-local
          RESOLVE_REPO: npm-virtual
          JFROG_TASK_DEBUG: "true"
          JFROG_CLI_LOG_LEVEL: debug
    steps:
      - name: build_and_publish_task
        type: Bash
        configuration:
          inputResources:
            - name: {{ .Values.primaryResource }}
              trigger: false
          integrations:
            - name: {{ .Values.artIntegration }}
        execution:
          onExecute:
            # Make sure version was provided
            - test -n "$TASK_VERSION" -a "$TASK_VERSION" != "0.0.0"
            - pushd $res_{{ .Values.primaryResource }}_resourcePath
            - popd
            # Run publish task
            - task: jfrog/publish-task@v0.2.1
              id: publish-{{ .Values.taskName }}
              repository: pipelines-tasks-dev-remote
              input:
                path: $res_{{ .Values.primaryResource }}_resourcePath
                integration: {{ .Values.artIntegration }}
                targetRepository: $TASK_REPOSITORY
                taskName: $TASK_NAME
                taskVersion: $TASK_VERSION
                includePattern: ^README.md$
